# Generated by Django 6.0.7 on 2026-07-21 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='document',
            name='doc_type',
            field=models.CharField(blank=True, choices=[('invoice', 'Invoice'), ('shipping', 'Shipping'), ('receipt', 'Receipt'), ('other', 'Other')], db_index=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='document',
            name='fournisseur',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='document',
            name='langue',
            field=models.CharField(blank=True, choices=[('fr', 'Français'), ('en', 'English'), ('ar', 'العربية'), ('autre', 'Autre')], max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='document',
            name='montant_ttc',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='document',
            name='numero',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
