# Generated by Django 6.0.7 on 2026-07-21 12:14

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai', '0002_document_date_document_doc_type_document_fournisseur_and_more'),
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SpreadsheetImport',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('file', models.FileField(upload_to='spreadsheets/%Y/%m/')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('mapped', 'Mapped'), ('confirmed', 'Confirmed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('data_type', models.CharField(blank=True, max_length=50, null=True)),
                ('column_mapping', models.JSONField(blank=True, null=True)),
                ('sample_rows', models.JSONField(blank=True, null=True)),
                ('normalized_rows', models.JSONField(blank=True, null=True)),
                ('row_count', models.IntegerField(blank=True, null=True)),
                ('needs_review', models.BooleanField(default=True)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='spreadsheet_imports', to='api.company')),
            ],
        ),
    ]
